### PR TITLE
Add CONFIG_HIGHMEM to all embeddedTS defconfigs.

### PR DESCRIPTION
**Pull request by luckshot**
Add HIGHMEM to the tsa38x kernels, both regular and minimal.

### CODE REVIEW

**Comment by ts-kris** [comment]
What is this needed for? I'm not opposed to adding it I had just thought that the CPU wouldn't need to map more than 4 GB through its whole address range.

**Comment by luckshot** [comment]
> What is this needed for? I'm not opposed to adding it I had just thought that the CPU wouldn't need to map more than 4 GB through its whole address range.

Turns out we need highmem to access the upper quarter of a gig of RAM.  I noticed the kernel complaining about ignoring an address range:
[    0.000000] Ignoring RAM at 0x30000000-0x40000000
[    0.000000] Consider using a HIGHMEM enabled kernel.
...
[    0.000000] Memory: 767772K/786432K available (7168K kernel code, 325K rwdata, 1792K rodata, 1024K init, 168K bss, 18660K reserved, 0K cma-reserved)


Then I checked Free, which reported only a total of 750Mi, so I added HIGHMEM and rechecked.

With HIGHMEM, we get 1.0 Gi total reported by Free and the kernel boot seems happier:
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x000000002fffffff]
[    0.000000]   HighMem  [mem 0x0000000030000000-0x000000003fffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000003fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x000000003fffffff]
[    0.000000] percpu: Embedded 15 pages/cpu s31372 r8192 d21876 u61440
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 260416
...
[    0.000000] Memory: 1027592K/1048576K available (7168K kernel code, 326K rwdata, 1796K rodata, 1024K init, 185K bss, 20984K reserved, 0K cma-reserved, 262144K highmem)

**Review by ts-kris — DISMISSED** [review]
Dang. Good find.

Untested but I suspect little issue with this change.

Per request, once approved I'll hold off on merging until backend tests are in place.

**Review by randytsi369 — COMMENTED** [review]
Reviewed, not tested.

**Review by randytsi369 — APPROVED** [review]

**Review by ts-kris — APPROVED** [review]
Not tested.

Will still wait on merging PR until testing for this is implemented.

**Comment by ts-kris** [comment]
All CI tests passed with new test to check mem sizes rolled out.

**Pull request merged**
