### PR TITLE
Update to v5.10.219

### PR DESCRIPTION
**Pull request by DaftB0t**
Sync with upstream v5.10.219

### CODE REVIEW

**Comment by ts-kris** [comment]
Looks like it was a transient build failure, rerunning tests.

**Review by ts-kris — DISMISSED** [review]
All checks passing now.

**Review by ts-kris — DISMISSED** [review]
Re-approved after .218 merged

**Review by markfeathers — DISMISSED** [review]
Passed CI testing

**Review by ts-kris — DISMISSED** [review]
3rd approve is the charm!

**Review by lionel — DISMISSED** [review]

**Review by ts-kris — DISMISSED** [review]

**Pull request merged**
