### PR TITLE
spidev warning fix

### PR DESCRIPTION
**Pull request by markfeathers**

### CODE REVIEW

**Comment by ts-kris** [comment]
I know this is only a draft but I'm immediately going to comment. Please use `technologic,spi-header` to match our existing in-kernel prefix name: https://github.com/embeddedTS/linux-lts/blob/linux-5.10.y/Documentation/devicetree/bindings/vendor-prefixes.yaml#L1058-L1059

We decided to not to approach changing this name upstream, yet, and we can certainly consider it again. However, keep it `technologic` for the time being so when we push changes upstream and mirror them here, we don't have to hunt down multiple references.

**Review by ts-kris — CHANGES_REQUESTED** [review]
Fix the commit title of cc146a2 and you've otherwise got my approval.

**Comment by markfeathers** [comment]
That should be fixed now

**Review by randytsi369 — APPROVED** [review]

**Review by ts-kris — APPROVED** [review]
Looks good to me. Not tested.

**Pull request merged**
