### PR TITLE
Initial TS-7670 Support

### PR DESCRIPTION
**Pull request by ts-kris**
Requires #11 to be merged in first.

### CODE REVIEW

**Review by randytsi369 — DISMISSED** [review]
Changes have been reviewed. No issues that I am aware of, but I have not tested these updates.

**Comment by ts-kris** [comment]
Pushed a typo fix and some formatting cleanup. Re-ran all tests successfully.

**Review by randytsi369 — DISMISSED** [review]
Changes have been re-reviewed. No issues that I am aware of, but I have not tested these updates.

**Comment by ts-kris** [comment]
In order for these changes to be effective and functional, in addition to #11 being merged, testing also needs to take place with this update U-Boot binary in place on the boot media: https://files.embeddedts.com/ts-arm-sbc/ts-7670-linux/binaries/u-boot/ts7670-20230301.sd

**Review by markfeathers — APPROVED** [review]

**Review by randytsi369 — APPROVED** [review]

**Pull request merged**
