### PR TITLE
irq-ts71xxweim: Add IRQ polarity

### PR DESCRIPTION
**Pull request by markfeathers**

### CODE REVIEW

**Review by ts-kris — DISMISSED** [review]
Did not test, I'm not terribly familiar with the interrupt API, but, all of the changes look solid to me.

**Comment by ts-kris** [comment]
Rebased to linux-5.10.y, no code changes.

**Review by luckshot — DISMISSED** [review]
I did not test, but read-through looks copasetic.

**Review by randytsi369 — DISMISSED** [review]

**Comment by ts-kris** [comment]
Since this is a pretty significant change, @lionel can you also review before we merge?

**Review by lionel — APPROVED** [review]
I read through the changes and saw no issues. Did not run it yet.

**Review by ts-kris — APPROVED** [review]
Re-approve after this PR was used to test CI integration. Untested.

**Pull request merged**
