### PR TITLE
Split platform configs

### PR DESCRIPTION
**Pull request by markfeathers**
The ts_defconfig can support multiple architectures, but not very efficiently.  We are instead supporting all of our architectures with:

        <tsarch>_defconfig
                * Includes broad hardware/software support
        <tsarch>_minimal_defconfig
                * Includes support to boot under debian

The pending ts-7250-v3 support pull request will include the tsimx6ul support.  This branch will add the remaining current platform support and remove the ts_defconfig.

### CODE REVIEW

**Review by ts-kris — DISMISSED** [review]
Tested tsimx6 and tsimx6_minimal under Debian and Buildroot for:
TS-7970
TS-4900

tsimx28 variants were not tested but defconfigs were reviewed and discussed.

**Comment by ts-kris** [comment]
Note that as of 499ce8d05a8662614891ef5ed353d9ba518bb795, tsimx6_defconfig is too large to boot in our U-Boots and needs to be slimmed down.

The two commits I added on top are changes that should happen to tsimx6_defconfig and tsimx6_minimal_defconfig to add ath10k support as well as clean up others. See each commit comment for details. Those changes should be squashed/fixedup in to prior commits, no reason to leave them as standalone.

**Comment by ts-kris** [comment]
Touched a couple of tsimx6 configs, these should be squashed back before final merge.

Also touched a couple FDTs to enable the on-board USB ethernet to correctly obtain a MAC address of (CPU MAC+1).

**Comment by ts-kris** [comment]
High level functionality testing and error checking with both full and minimal defconfigs performed on:
- TS-7970 (solo/quad, different PCB revs, HDMI external monitor, Wi-Fi, etc.)
- TS-TPC-8390-4900 (quad, different PCB revs, different Wi-Fi devices, etc.)
- TS-TPC-8950-4900 (quad, different PCB revs, different Wi-Fi devices, etc.)
- TS-7670 (different build configurations)
- TS-7400-V2 (Rev B)
- TS-7553-V2 (different build configurations)
- TS-8551-4100 (different build configurations)

**Review by ts-kris — APPROVED** [review]

**Comment by markfeathers** [comment]
Tested against the TS-7250-V3 on both 6ul configs, tested features on both tsimx6 configs on a 4900+8390.  The rest looks good to me.

**Review by luckshot — APPROVED** [review]

**Pull request merged**
